baseURL = "https://blog.azazelm3dj3d.com"
title = "azazelm3dj3d's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "azazelm3dj3d"
  description = "Software Developer"
  github = "azazelm3dj3d"
  url = "https://azazelm3dj3d.com"
  keywords = "azazelm3dj3d blog, software development, programming, cybersecurity, azazelm3dj3d, open-source developer, open source"
  rss = true
  lastmod = true
  favicon = "https://avatars.githubusercontent.com/u/56496067"
  location = "~"
  userStatusEmoji = "💀"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
